"use client";
import { useState, useRef, useEffect } from "react";
import { ArrowUp, ImagePlus, X } from "lucide-react";
import { getAccessToken, supabase } from "@/lib/supabase";

export interface ChatMessage { role: "user" | "assistant"; content: string; timestamp: string; image?: string; }
function now(){return new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});}
function dbTime(value:string){try{return new Date(value).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});}catch{return now();}}
function norm(value:string){return value.trim().toLowerCase().replace(/\s+/g," ");}
function wantsPaper(value:string){const v=norm(value);return v.includes("paper trading")||v.includes("paper trade");}
function wantsLive(value:string){const v=norm(value);return v.includes("live trade")||v.includes("live trading")||v.includes("start live");}

export function ChatPanel({strategyId,initialMessages,onboarding=false}:{strategyId?:string;initialMessages?:ChatMessage[];onboarding?:boolean}){
 const [messages,setMessages]=useState<ChatMessage[]>(initialMessages??[]); const [input,setInput]=useState(""); const [image,setImage]=useState<string>();
 const [sending,setSending]=useState(false); const [historyLoading,setHistoryLoading]=useState(!!strategyId); const [paperChoicePending,setPaperChoicePending]=useState(false); const [liveApprovalPending,setLiveApprovalPending]=useState(false);
 const scrollRef=useRef<HTMLDivElement>(null); const fileRef=useRef<HTMLInputElement>(null);

 useEffect(()=>{let mounted=true;(async()=>{if(!strategyId){setHistoryLoading(false);return;}setHistoryLoading(true);const {data,error}=await supabase.from("chat_messages").select("role,content,created_at").eq("strategy_id",strategyId).order("created_at",{ascending:true}).order("id",{ascending:true}).limit(500);if(!mounted)return;if(!error&&data?.length)setMessages(data.map((m:any)=>({role:m.role,content:m.content,timestamp:dbTime(m.created_at)})));else if(!error&&initialMessages?.length)setMessages(initialMessages);setHistoryLoading(false);})();return()=>{mounted=false}},[strategyId]);
 useEffect(()=>{if(!onboarding||messages.length)return;let mounted=true;supabase.auth.getUser().then(({data})=>{if(!mounted)return;const u=data.user;const md=(u?.user_metadata??{}) as Record<string,unknown>;const name=String(md.full_name||md.name||md.first_name||u?.email?.split("@")[0]||"there").trim();setMessages([{role:"assistant",content:`Hello ${name} 👋\n\nWelcome to ManiQuantAI. I'm your AI trading strategy partner. Tell me what you want to trade and how you want to trade it.\n\nYou can also attach a chart screenshot by clicking the image button, pasting it with Ctrl+V, or dragging it into this chat.`,timestamp:now()}]);});return()=>{mounted=false}},[onboarding,messages.length]);
 useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:"smooth"})},[messages]);

 async function persist(role:"user"|"assistant",content:string){if(!strategyId||!content.trim())return;const {error}=await supabase.from("chat_messages").insert({strategy_id:strategyId,role,content:content.trim()});if(error)console.warn("Could not persist chat message",error.message);}
 function addAssistant(content:string){setMessages(m=>[...m,{role:"assistant",content,timestamp:now()}]);void persist("assistant",content);}
 function acceptImage(file?:File){if(!file||!file.type.startsWith("image/"))return;if(file.size>8*1024*1024){addAssistant("That chart image is larger than 8 MB. Please use a smaller PNG, JPG, or WebP screenshot.");return;}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file);}
 function onPaste(e:React.ClipboardEvent){const item=Array.from(e.clipboardData.items).find(i=>i.type.startsWith("image/"));if(item){e.preventDefault();acceptImage(item.getAsFile()||undefined);}}

 async function backendMessage(content:string,attached?:string,showUser=true){
   const token=await getAccessToken(); if(!strategyId)throw new Error("Create or select a strategy first so I can analyse it.");
   const display=attached?`${content}\n\n[Chart screenshot attached]`:content;
   if(showUser){setMessages(m=>[...m,{role:"user",content,timestamp:now(),image:attached}]);await persist("user",display);}
   const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json",Accept:"text/event-stream",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({strategy_id:strategyId,message:content,image:attached||null})});
   if(!res.ok){const detail=await res.text();throw new Error(`AI service returned ${res.status}: ${detail.slice(0,220)}`)}
   const ct=res.headers.get("content-type")||""; const ts=now(); let final="";
   if(ct.includes("application/json")){const p=await res.json();final=p.content||p.message||"The request completed.";setMessages(m=>[...m,{role:"assistant",content:final,timestamp:ts}]);await persist("assistant",final);return final;}
   if(!res.body)throw new Error("AI service returned no response body."); const reader=res.body.getReader();const decoder=new TextDecoder();let buffer="",text="",added=false;
   const upsert=(next:string)=>{final=next;setMessages(m=>{const base=added?m.slice(0,-1):m;added=true;return[...base,{role:"assistant",content:next,timestamp:ts}]})};
   while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split("\n\n");buffer=events.pop()??"";for(const event of events){const line=event.split("\n").find(x=>x.startsWith("data:"));if(!line)continue;try{const p=JSON.parse(line.slice(5).trim());if(p.type==="delta"){text+=p.content??"";if(text)upsert(text)}else if(p.type==="error")throw new Error(p.message??"AI service failed")}catch(e){if(e instanceof Error&&e.message!=="Unexpected end of JSON input")throw e}}}
   if(!added)upsert("The AI completed the request but returned no text. Check the strategy status for agent progress."); if(final)await persist("assistant",final); return final;
 }

 async function startLiveTrading(){if(!strategyId)return;setSending(true);try{const token=await getAccessToken();const res=await fetch("/api/paper-decision",{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({strategy_id:strategyId,decision:"live_start"})});const p=await res.json();if(!res.ok)throw new Error(p.detail||p.message||"Live trading is not ready.");addAssistant(p.message||"Live trading started.");}catch(e){addAssistant(`I couldn't start live trading.\n\n${e instanceof Error?e.message:"Request failed."}`)}finally{setSending(false)}}
 async function paperDecision(decision:"yes"|"no"|"live_yes"|"live_no"){if(!strategyId)return;const label=decision==="yes"?"Yes":decision==="no"?"No":decision==="live_yes"?"Approve live":"No";setMessages(m=>[...m,{role:"user",content:label,timestamp:now()}]);await persist("user",label);setSending(true);try{const token=await getAccessToken();const res=await fetch("/api/paper-decision",{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({strategy_id:strategyId,decision})});const p=await res.json();if(!res.ok)throw new Error(p.detail||p.message||"Could not update the trading gate.");if(decision==="yes"){setPaperChoicePending(false);addAssistant(p.message||"Yes selected.");await backendMessage("do paper trading",undefined,false)}else if(decision==="no"){setPaperChoicePending(false);setLiveApprovalPending(true);addAssistant(p.message||"Paper trading skipped. Do you explicitly approve live trading?")}else if(decision==="live_yes"){setLiveApprovalPending(false);addAssistant(p.message||"Live trading approved.")}else addAssistant(p.message||"Live trading remains locked.")}catch(e){addAssistant(`I couldn't update the trading gate.\n\n${e instanceof Error?e.message:"Request failed."}`)}finally{setSending(false)}}
 async function sendMessage(){const content=input.trim();if((!content&&!image)||sending)return;setInput("");const attached=image;setImage(undefined);if(wantsLive(content)){setMessages(m=>[...m,{role:"user",content,timestamp:now(),image:attached}]);await persist("user",attached?`${content}\n\n[Chart screenshot attached]`:content);await startLiveTrading();return;}if(wantsPaper(content)&&!paperChoicePending&&!liveApprovalPending){setMessages(m=>[...m,{role:"user",content,timestamp:now(),image:attached}]);await persist("user",content);setPaperChoicePending(true);addAssistant("Before I start paper trading, do you want to run the strategy in paper mode first?\n\nYes — run paper trading first.\nNo — skip paper trading and request separate live-trading approval.");return;}setSending(true);try{await backendMessage(content||"Please analyse this chart screenshot.",attached,true)}catch(e){const t=`I couldn't complete that request.\n\n${e instanceof Error?e.message:"AI service request failed."}`;setMessages(m=>[...m,{role:"assistant",content:t,timestamp:now()}]);await persist("assistant",t)}finally{setSending(false)}}

 return <div className="flex h-full min-h-[520px] flex-col lg:border-l lg:border-border">
  <div className="flex items-center justify-between border-b border-border px-5 py-3"><span className="text-xs uppercase tracking-wide text-text-muted">ManiQuant AI</span><span className="flex items-center gap-1.5 rounded-md border border-border bg-bg-raised px-2 py-0.5 text-xs text-text-muted"><span className="h-1.5 w-1.5 rounded-full bg-accent"/>Ready</span></div>
  <div ref={scrollRef} onPaste={onPaste} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();acceptImage(e.dataTransfer.files?.[0])}} className="flex-1 space-y-4 overflow-y-auto px-5 py-4">
   {historyLoading?<div className="text-center text-xs text-text-faint py-6">Loading chat history…</div>:messages.map((m,i)=><div key={i} className={m.role==="user"?"flex justify-end":"flex justify-start"}><div className={["max-w-[90%] rounded-lg px-4 py-3 text-sm leading-relaxed",m.role==="user"?"bg-accent-dim text-text border border-accent/20":"bg-bg-panel text-text border border-border"].join(" ")}>{m.image&&<img src={m.image} alt="Attached trading chart" className="mb-3 max-h-72 max-w-full rounded-md border border-border object-contain"/>}<p className="whitespace-pre-line">{m.content}</p><span className="mt-2 block text-[10px] text-text-faint">{m.role==="user"?"You":"ManiQuant AI"} · {m.timestamp}</span></div></div>)}
   {paperChoicePending&&<div className="flex gap-2"><button onClick={()=>paperDecision("yes")} disabled={sending} className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-bg disabled:opacity-50">Yes</button><button onClick={()=>paperDecision("no")} disabled={sending} className="rounded-md border border-border bg-bg-panel px-4 py-2 text-sm text-text disabled:opacity-50">No</button></div>}
   {liveApprovalPending&&<div className="flex gap-2"><button onClick={()=>paperDecision("live_yes")} disabled={sending} className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-bg disabled:opacity-50">Approve live</button><button onClick={()=>paperDecision("live_no")} disabled={sending} className="rounded-md border border-border bg-bg-panel px-4 py-2 text-sm text-text disabled:opacity-50">No</button></div>}
   {sending&&<div className="flex justify-start"><div className="rounded-lg border border-border bg-bg-panel px-4 py-2.5 text-sm text-text-faint">Analysing…</div></div>}
  </div>
  <div className="border-t border-border p-4" onPaste={onPaste} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();acceptImage(e.dataTransfer.files?.[0])}}>
   {image&&<div className="mb-2 flex items-center gap-2 rounded-md border border-border bg-bg-raised p-2"><img src={image} alt="Chart preview" className="h-16 w-24 rounded object-cover"/><span className="flex-1 text-xs text-text-muted">Chart screenshot attached</span><button type="button" onClick={()=>setImage(undefined)} className="rounded p-1 text-text-muted hover:text-text" aria-label="Remove image"><X size={15}/></button></div>}
   <div className="flex items-center gap-2 rounded-lg border border-border bg-bg-panel px-3 py-2"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>acceptImage(e.target.files?.[0])}/><button type="button" onClick={()=>fileRef.current?.click()} disabled={sending||!strategyId} className="flex h-7 w-7 items-center justify-center rounded-md text-text-muted hover:bg-bg-raised hover:text-text disabled:opacity-40" aria-label="Attach chart screenshot" title="Attach chart screenshot"><ImagePlus size={17}/></button><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendMessage()} placeholder="Tell ManiQuant AI what you want to trade… Paste or drag a chart screenshot" className="flex-1 bg-transparent text-sm text-text placeholder:text-text-faint outline-none"/><button onClick={sendMessage} disabled={sending||!strategyId||(!input.trim()&&!image)} className="flex h-7 w-7 items-center justify-center rounded-md bg-accent text-bg disabled:opacity-40" aria-label="Send message"><ArrowUp size={14}/></button></div>
   <div className="mt-1.5 text-[10px] text-text-faint">PNG, JPG or WebP · up to 8 MB · paste with Ctrl+V or drag and drop</div>
  </div>
 </div>;
}
