"use client";

import { useEffect, useState } from "react";
import { X, Copy, CheckCircle2, Monitor, ShieldCheck, RefreshCw, Ban, Download, ExternalLink } from "lucide-react";
import { getAccessToken } from "@/lib/supabase";

const EA_SOURCE_URL="/api/mt5-bridge/download";
const EA_DOCS_URL="https://github.com/maniquantai-code/Maniquantai/blob/main/mt5-bridge/ea/README.md";

export function ConnectMT5Modal({open,onClose,onConnected}:{open:boolean;onClose:()=>void;onConnected?:(accountId:string)=>void}){
 const [connecting,setConnecting]=useState(false); const [error,setError]=useState<string|null>(null); const [bridgeToken,setBridgeToken]=useState<string|null>(null); const [accountId,setAccountId]=useState<string|null>(null); const [copied,setCopied]=useState(false); const [status,setStatus]=useState<any>(null); const [loadingStatus,setLoadingStatus]=useState(false);
 useEffect(()=>{if(open){setError(null);setBridgeToken(null);loadStatus()}},[open]);
 if(!open)return null;
 async function authHeaders(){const token=await getAccessToken();if(!token)throw new Error("Please sign in again before managing MetaTrader 5.");return {Authorization:`Bearer ${token}`};}
 async function readError(res:Response,fallback:string){const body=await res.json().catch(()=>null);return typeof body?.detail==="string"?body.detail:fallback;}
 async function loadStatus(){setLoadingStatus(true);try{const h=await authHeaders();const res=await fetch("/api/mt5-bridge/status",{headers:h});if(res.ok)setStatus(await res.json())}catch{}finally{setLoadingStatus(false)}}
 async function createOrRefresh(path:"register"|"refresh"){
  setError(null);setConnecting(true);
  try{const h=await authHeaders();const res=await fetch(`/api/mt5-bridge/${path}`,{method:"POST",headers:h});if(!res.ok)throw new Error(await readError(res,"Could not create the secure MT5 connection."));const data=await res.json();if(!data?.bridge_token)throw new Error("The secure MT5 connection token was not returned.");setBridgeToken(data.bridge_token);setAccountId(data.broker_account_id||null);setStatus({connected:true,bridge_enabled:true,expires_at:data.expires_at});if(data.broker_account_id)onConnected?.(data.broker_account_id)}catch(e){setError(e instanceof Error?e.message:"Could not manage MetaTrader 5 token.")}finally{setConnecting(false)}
 }
 async function revoke(){setError(null);try{const h=await authHeaders();const res=await fetch("/api/mt5-bridge/revoke",{method:"POST",headers:h});if(!res.ok)throw new Error(await readError(res,"Could not revoke the bridge token."));setBridgeToken(null);await loadStatus();onConnected?.(accountId||"")}catch(e){setError(e instanceof Error?e.message:"Could not revoke the bridge token.")}}
 async function copyToken(){if(!bridgeToken)return;await navigator.clipboard.writeText(bridgeToken);setCopied(true);setTimeout(()=>setCopied(false),1600)}
 const expires=status?.expires_at?new Date(status.expires_at):null; const online=status?.last_verified_at && Date.now()-new Date(status.last_verified_at).getTime()<30000;
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/60" onClick={onClose}/><div className="relative max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-xl border border-border bg-bg-panel p-6 shadow-xl">
  <div className="mb-1 flex items-center justify-between"><h2 className="text-base font-semibold">Connect MetaTrader 5</h2><button onClick={onClose} className="text-text-muted hover:text-text" aria-label="Close"><X size={18}/></button></div>
  <p className="mt-2 text-sm leading-6 text-text-muted">Connect your own MT5 terminal to ManiQuantAI. Your broker password is <strong className="text-text">never entered into ManiQuantAI</strong>.</p>
  {loadingStatus?<p className="mt-4 text-xs text-text-faint">Checking bridge token status…</p>:<div className="mt-4 rounded-lg border border-border bg-bg-raised p-4 text-xs"><div className="flex items-center justify-between"><span className="font-medium text-text">Bridge authorization</span><span className={online?"text-accent":"text-text-faint"}>{online?"● Online":"○ Offline"}</span></div>{status?.connected&&<div className="mt-2 space-y-1 text-text-faint"><div>Token: {status.bridge_enabled?"Active":"Revoked"}</div>{expires&&<div>Expires: {expires.toLocaleString()}</div>}</div>}</div>}
  {!bridgeToken ? <>
   <div className="mt-5 grid gap-3 sm:grid-cols-3"><Info icon={<ShieldCheck size={16}/>} title="Secure token" text="Only a hash is stored in Supabase. The full token is shown once."/><Info icon={<Monitor size={16}/>} title="Your computer" text="MT5 runs on your Windows PC. No ManiQuantAI VPS is required."/><Info icon={<CheckCircle2 size={16}/>} title="You control it" text="Revoke the bridge any time from this screen."/></div>
   <div className="mt-5 rounded-lg border border-border bg-bg-raised p-4 text-xs text-text-muted"><div className="font-medium text-text">How it works</div><ol className="mt-2 list-decimal space-y-1.5 pl-4"><li>Download the ManiQuantAI MT5 EA source below.</li><li>Compile it in MetaEditor to create the <code>.ex5</code> EA.</li><li>Generate a personal token and copy it.</li><li>Attach the EA to your MT5 chart, enter the token, and enable Algo Trading.</li></ol></div>
   <div className="mt-4 flex flex-col gap-2 sm:flex-row"><a href={EA_SOURCE_URL} download="ManiQuantAI_MT5_Bridge.mq5" className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium text-text hover:bg-bg-raised"><Download size={15}/> Download EA source</a><a href={EA_DOCS_URL} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm text-text-muted hover:bg-bg-raised"><ExternalLink size={14}/> Installation guide</a></div>
   <p className="mt-2 text-[11px] leading-4 text-text-faint">The source downloads directly from ManiQuantAI. The final <code>.ex5</code> binary must be compiled with MetaTrader 5 MetaEditor.</p>
   {error&&<div className="mt-3 rounded-lg border border-danger/25 bg-danger/5 p-3 text-sm text-danger">{error}</div>}
   <div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-border px-4 py-2 text-sm text-text-muted">Close</button>{status?.bridge_enabled&&<><button onClick={()=>createOrRefresh("refresh")} disabled={connecting} className="flex items-center gap-1 rounded-lg border border-border px-4 py-2 text-sm text-text-muted"><RefreshCw size={14}/> Refresh token</button><button onClick={revoke} className="flex items-center gap-1 rounded-lg border border-danger/30 px-4 py-2 text-sm text-danger"><Ban size={14}/> Revoke</button></>}<button onClick={()=>createOrRefresh("register")} disabled={connecting} className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-bg">{connecting?"Generating…":status?.bridge_enabled?"Generate new token":"Generate token"}</button></div>
  </> : <div className="space-y-4">
   <div className="rounded-lg border border-accent/30 bg-accent-dim p-4"><p className="text-xs font-medium text-accent">New MT5 bridge token created</p><p className="mt-1 text-xs leading-5 text-text-muted">The previous token is no longer valid. Copy this token into the EA now.</p></div>
   <div><label className="mb-1 block text-xs text-text-muted">Bridge token</label><div className="flex gap-2"><code className="min-w-0 flex-1 break-all rounded-lg border border-border bg-bg px-3 py-2 text-[11px] text-text">{bridgeToken}</code><button onClick={copyToken} className="shrink-0 rounded-lg border border-border px-3 text-xs text-text-muted hover:text-text" aria-label="Copy bridge token">{copied?<CheckCircle2 size={16}/>:<Copy size={16}/>}</button></div></div>
   <div className="rounded-lg border border-border bg-bg-raised p-4 text-xs leading-5 text-text-muted"><strong className="text-text">Next:</strong> Open MetaEditor → compile <code>ManiQuantAI_MT5_Bridge.mq5</code> → place the resulting <code>.ex5</code> in <code>MQL5/Experts</code> → attach it to a chart → paste this token into the EA inputs → enable Algo Trading.</div>
   <div className="flex flex-col gap-2 sm:flex-row"><a href={EA_SOURCE_URL} download="ManiQuantAI_MT5_Bridge.mq5" className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium text-text hover:bg-bg-raised"><Download size={15}/> Download EA source</a><a href={EA_DOCS_URL} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm text-text-muted hover:bg-bg-raised"><ExternalLink size={14}/> Guide</a></div>
   {expires&&<p className="text-xs text-text-faint">Token expires {expires.toLocaleString()}. Refresh it from this screen before expiry.</p>}
   <button onClick={onClose} className="w-full rounded-lg bg-accent px-4 py-2 text-sm font-medium text-bg">Done</button>
  </div>}
 </div></div>
}
function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-lg border border-border bg-bg-raised p-3"><div className="flex items-center gap-2 text-accent">{icon}<span className="text-xs font-medium text-text">{title}</span></div><p className="mt-1.5 text-[11px] leading-4 text-text-faint">{text}</p></div>}
