"use client";
import { useState } from "react";
import { X } from "lucide-react";
import { getAccessToken } from "@/lib/supabase";

export function ConnectBrokerApiModal({open,onClose,onConnected}:{open:boolean;onClose:()=>void;onConnected?:()=>void}){
 const [brokerName,setBrokerName]=useState(""); const [label,setLabel]=useState(""); const [apiUrl,setApiUrl]=useState(""); const [apiKey,setApiKey]=useState(""); const [apiSecret,setApiSecret]=useState(""); const [authType,setAuthType]=useState("bearer");
 const [dataPath,setDataPath]=useState(""); const [timestampPath,setTimestampPath]=useState("timestamp"); const [openPath,setOpenPath]=useState("open"); const [highPath,setHighPath]=useState("high"); const [lowPath,setLowPath]=useState("low"); const [closePath,setClosePath]=useState("close");
 const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [error,setError]=useState<string|null>(null);
 if(!open)return null;
 async function submit(e:React.FormEvent){ e.preventDefault(); setError(null); if(!brokerName.trim()||!apiUrl.trim()||!apiKey.trim()){setError("Enter the broker app name, HTTPS market-data API URL, and API key.");return} setSaving(true);
  try{ const token=await getAccessToken(); if(!token)throw new Error("Please sign in again before connecting a broker."); const res=await fetch("/api/broker-accounts/api",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({broker_name:brokerName.trim(),label:label||undefined,api_url:apiUrl.trim(),api_key:apiKey,api_secret:apiSecret||undefined,auth_type:dataPath?authType:authType,data_path:dataPath,timestamp_path:timestampPath,open_path:openPath,high_path:highPath,low_path:lowPath,close_path:closePath})}); const body=await res.json().catch(()=>null); if(!res.ok)throw new Error(body?.detail||"Could not save the broker API connection."); setSaved(true); onConnected?.();
  }catch(err){setError(err instanceof Error?err.message:"Could not save the broker API connection.")}finally{setSaving(false)} }
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/60" onClick={onClose}/><div className="relative max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-lg border border-border bg-bg-panel p-6"><div className="mb-1 flex items-center justify-between"><h2 className="text-base font-semibold">Connect Broker App / API</h2><button onClick={onClose} aria-label="Close" className="text-text-muted hover:text-text"><X size={18}/></button></div>
 {saved?<div className="space-y-4"><div className="rounded-lg border border-accent/30 bg-accent-dim p-3"><p className="text-xs font-medium text-accent">Broker API saved successfully</p><p className="mt-1 text-xs text-text-muted">ManiQuantAI will use this connector for market data when it is the selected primary account. API secrets are encrypted server-side.</p></div><button onClick={onClose} className="w-full rounded-lg bg-accent px-4 py-2 text-sm font-medium text-bg">Done</button></div>
 :<form onSubmit={submit} className="mt-4 space-y-3"><p className="text-xs text-text-faint">Use this for brokers/apps that do not use MetaTrader 5. The API must return OHLC candle data. You can use placeholders <code>{"{symbol}"}</code>, <code>{"{timeframe}"}</code>, <code>{"{start}"}</code>, and <code>{"{end}"}</code> in the URL.</p>
  <div className="grid grid-cols-2 gap-3"><Field label="Broker / app name" value={brokerName} set={setBrokerName} placeholder="e.g. Interactive Brokers"/><Field label="Nickname (optional)" value={label} set={setLabel} placeholder="My broker"/></div>
  <Field label="Market-data API URL" value={apiUrl} set={setApiUrl} placeholder="https://api.example.com/candles?symbol={symbol}&interval={timeframe}"/>
  <div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs text-text-muted">Authentication</label><select value={authType} onChange={e=>setAuthType(e.target.value)} className="w-full rounded-lg border border-border bg-bg px-3 py-2 text-sm text-text"><option value="bearer">Bearer token</option><option value="x-api-key">X-API-Key</option><option value="basic">Basic auth</option></select></div><Field label="API key / username" value={apiKey} set={setApiKey} placeholder="••••••••" secret/></div>
  <Field label="API secret (optional)" value={apiSecret} set={setApiSecret} placeholder="••••••••" secret/>
  <details className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-xs font-medium text-text-muted">Response mapping (advanced)</summary><div className="mt-3 space-y-3"><Field label="Candle array JSON path" value={dataPath} set={setDataPath} placeholder="data or candles (leave empty for auto-detect)"/><div className="grid grid-cols-2 gap-3"><Field label="Timestamp field / index" value={timestampPath} set={setTimestampPath} placeholder="timestamp"/><Field label="Open field / index" value={openPath} set={setOpenPath} placeholder="open"/><Field label="High field / index" value={highPath} set={setHighPath} placeholder="high"/><Field label="Low field / index" value={lowPath} set={setLowPath} placeholder="low"/><Field label="Close field / index" value={closePath} set={setClosePath} placeholder="close"/></div></div></details>
  {error&&<div className="rounded-lg border border-danger/25 bg-danger/5 p-3 text-sm text-danger">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-border px-4 py-2 text-sm text-text-muted">Cancel</button><button disabled={saving} className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-bg disabled:opacity-40">{saving?"Saving…":"Connect broker"}</button></div>
 </form>}</div></div>
}
function Field({label,value,set,placeholder,secret}:{label:string;value:string;set:(v:string)=>void;placeholder?:string;secret?:boolean}){return <div><label className="mb-1 block text-xs text-text-muted">{label}</label><input type={secret?"password":"text"} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-border bg-bg px-3 py-2 text-sm text-text"/></div>}
