"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, LogOut, Plus, Trash2, Wifi, Star, Monitor } from "lucide-react";
import { supabase, getAccessToken } from "@/lib/supabase";
import { useRouter } from "next/navigation";
import { ConnectMT5Modal } from "@/components/ConnectMT5Modal";
import { ConnectBrokerApiModal } from "@/components/ConnectBrokerApiModal";

interface Wallet { balance:number; monthly_allowance:number; reset_date:string|null; }
interface BrokerAccount { id:string; connector_type:string; connector_name:string; label:string|null; created_at:string; last_verified_at:string|null; is_primary?:boolean; }
const TIERS=[{name:"Free",priceIndia:"₹0",priceIntl:"$0",credits:80},{name:"Starter",priceIndia:"₹299",priceIntl:"$20",credits:500},{name:"Pro",priceIndia:"₹699",priceIntl:"$49",credits:1500},{name:"Elite",priceIndia:"₹1,499",priceIntl:"$99",credits:4000}];

function mt5Online(lastVerifiedAt:string|null){return !!lastVerifiedAt && Date.now()-new Date(lastVerifiedAt).getTime()<30000;}

export default function SettingsPage(){
 const [wallet,setWallet]=useState<Wallet|null>(null); const [accounts,setAccounts]=useState<BrokerAccount[]>([]); const [loading,setLoading]=useState(true); const [connectOpen,setConnectOpen]=useState(false); const [brokerOpen,setBrokerOpen]=useState(false); const router=useRouter();
 async function fetchAll(){try{const token=await getAccessToken();if(!token){setLoading(false);return}const [walletRes,accountsRes]=await Promise.all([fetch("/api/wallet",{headers:{Authorization:`Bearer ${token}`}}),fetch("/api/broker-accounts",{headers:{Authorization:`Bearer ${token}`}})]);if(walletRes.ok)setWallet(await walletRes.json());if(accountsRes.ok)setAccounts(await accountsRes.json())}catch{}finally{setLoading(false)}}
 useEffect(()=>{fetchAll();const timer=setInterval(fetchAll,10000);return()=>clearInterval(timer)},[]);
 async function handleSignOut(){await supabase.auth.signOut();router.push("/login")}
 async function handleDisconnect(id:string){const token=await getAccessToken();await fetch(`/api/broker-accounts/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});setAccounts(a=>a.filter(x=>x.id!==id));await fetchAll()}
 async function handlePrimary(id:string){const token=await getAccessToken();const res=await fetch(`/api/broker-accounts/${id}/primary`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});if(res.ok)await fetchAll()}
 const usedPercent=wallet?Math.round(((wallet.monthly_allowance-wallet.balance)/wallet.monthly_allowance)*100):0; const isLowOrOut=wallet?wallet.balance/wallet.monthly_allowance<.15:false; const currentTierName=wallet?TIERS.find(t=>t.credits===wallet.monthly_allowance)?.name??"Free":"Free";
 return <div className="min-h-screen bg-bg"><header className="flex items-center gap-3 border-b border-border px-4 py-3 sm:px-6"><Link href="/dashboard" className="text-text-muted hover:text-text" aria-label="Back"><ArrowLeft size={18}/></Link><span className="font-semibold">Settings & billing</span></header>
 <div className="mx-auto max-w-2xl space-y-6 p-4 sm:p-6">
  <section className="rounded-lg border border-border bg-bg-panel p-5"><h2 className="mb-3 text-xs uppercase tracking-wide text-text-muted">Credit balance</h2>{loading?<p className="text-sm text-text-faint">Loading…</p>:wallet?<><div className="mb-2 flex items-baseline justify-between"><span className="text-2xl font-semibold">{wallet.balance}</span><span className="text-sm text-text-muted">/ {wallet.monthly_allowance} credits</span></div><div className="h-2 overflow-hidden rounded-full bg-bg-raised"><div className={`h-full rounded-full transition-all ${isLowOrOut?"bg-warn":"bg-accent"}`} style={{width:`${100-usedPercent}%`}}/></div>{wallet.reset_date&&<p className="mt-2 text-xs text-text-faint">Resets {new Date(wallet.reset_date).toLocaleDateString()}</p>}{isLowOrOut&&<div className="mt-3 rounded-lg border border-warn/30 bg-warn-dim p-3"><p className="text-sm text-warn">{wallet.balance===0?"You're out of credits for this cycle.":"Running low on credits."} {currentTierName==="Free"?"Upgrade to Starter for a bigger monthly allowance and Claude-powered analysis.":"Upgrade for more credits and higher limits."}</p><button className="mt-2 rounded-md bg-warn px-3 py-1.5 text-xs font-medium text-bg">View plans</button></div>}</>:<p className="text-sm text-text-faint">Couldn&apos;t load balance — sign in and make sure the backend is reachable.</p>}</section>
  <section className="rounded-lg border border-border bg-bg-panel p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-xs uppercase tracking-wide text-text-muted">Linked trading accounts</h2><p className="mt-1 text-xs text-text-faint">MT5 runs on the user&apos;s own Windows computer; ManiQuantAI only sends approved jobs through the secure bridge.</p></div><div className="flex gap-2"><button onClick={()=>setBrokerOpen(true)} className="flex items-center gap-1 rounded-md border border-border px-2.5 py-1 text-xs font-medium text-text"><Plus size={12}/> Other Broker / API</button><button onClick={()=>setConnectOpen(true)} className="flex items-center gap-1 rounded-md bg-accent px-2.5 py-1 text-xs font-medium text-bg"><Plus size={12}/> Connect MT5</button></div></div>
   {accounts.length===0?<p className="text-sm text-text-faint">No trading accounts linked. Connect MT5 to let ManiQuantAI communicate with the MetaTrader terminal you already use with your broker.</p>:<div className="space-y-2">{accounts.map(acc=>{const online=acc.connector_type==="mt5"?mt5Online(acc.last_verified_at):false;return <div key={acc.id} className="flex items-center justify-between rounded-lg border border-border p-3"><div className="flex min-w-0 items-center gap-2"><div className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-md ${online?"bg-accent-dim text-accent":"bg-bg-raised text-text-faint"}`}><Monitor size={14}/></div><div className="min-w-0"><div className="flex items-center gap-2 text-sm"><span className="truncate">{acc.label||acc.connector_name}</span>{acc.is_primary&&<span className="rounded-full bg-accent px-2 py-0.5 text-[10px] font-medium text-bg">Primary</span>}</div><div className="text-xs text-text-faint">{acc.connector_type==="mt5"?"MetaTrader 5":"Broker API"} · {acc.connector_type==="mt5"?(online?"Bridge online":"Bridge offline"):acc.connector_name}</div></div></div><div className="flex items-center gap-3"><button onClick={()=>handlePrimary(acc.id)} disabled={acc.is_primary} className="text-text-faint hover:text-accent disabled:opacity-30" title="Use for market data" aria-label="Use for market data"><Star size={14} fill={acc.is_primary?"currentColor":"none"}/></button><button onClick={()=>handleDisconnect(acc.id)} className="text-text-faint hover:text-danger" aria-label="Disconnect"><Trash2 size={14}/></button></div></div>})}</div>}
   <p className="mt-3 text-xs text-text-faint">ManiQuantAI does not need your MT5 broker password. Log into MT5 normally on your own computer, then authorize the local bridge with the connection token. No ManiQuantAI VPS is required.</p>
  </section>
  <section className="rounded-lg border border-border bg-bg-panel p-5"><h2 className="mb-3 text-xs uppercase tracking-wide text-text-muted">Your plan</h2><div className="space-y-2">{TIERS.map(tier=><div key={tier.name} className={`flex items-center justify-between rounded-lg border p-3 ${tier.name===currentTierName?"border-accent bg-accent-dim":"border-border"}`}><div><div className="flex items-center gap-2"><span className="text-sm font-medium">{tier.name}</span>{tier.name===currentTierName&&<span className="rounded-full bg-accent px-2 py-0.5 text-[10px] font-medium text-bg">Current</span>}</div><span className="text-xs text-text-faint">{tier.credits} credits/month</span></div><div className="text-right text-sm text-text-muted">{tier.priceIndia} <span className="text-text-faint">/</span> {tier.priceIntl}</div></div>)}</div><p className="mt-3 text-xs text-text-faint">Credits are an internal usage unit, not a currency conversion — they cover research, backtesting, and chat depth. Trading safety mechanisms are identical at every tier.</p></section>
  <button onClick={handleSignOut} className="flex w-full items-center justify-center gap-2 rounded-lg border border-border py-2.5 text-sm text-text-muted hover:bg-bg-raised"><LogOut size={14}/> Sign out</button>
 </div><ConnectMT5Modal open={connectOpen} onClose={()=>setConnectOpen(false)} onConnected={()=>fetchAll()}/><ConnectBrokerApiModal open={brokerOpen} onClose={()=>setBrokerOpen(false)} onConnected={()=>fetchAll()}/></div>
}
